---
title: "Day 17 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(readr)
options(scipen = 999)
```

## Part 1

Begin by drawing in the input

```{r}
input<-read_lines("Day17Sample.txt")

containers<-c()
for(i in 1:length(input)){containers<-c(containers,as.numeric(input[i]))}
```

Create a dataframe & go through the elements one by one.

```{r}
containercombos<-function(cs=containers,t=25){
  df<-data.frame(c(0),c(0),c(0))
  colnames(df)<-c("total","possible","containercount")
  leftover<-cs
  while(length(leftover)>0){
    ct<-leftover[1]
    leftover<-leftover[-1]
    yesct<-df %>% rowwise %>% mutate(total=total+ct) %>% mutate(possible=total+sum(leftover)) %>% ungroup 
    noct<-df %>% rowwise %>% mutate(possible=total+sum(leftover)) %>% ungroup
    df<-rbind(yesct,noct)
    df<-df%>%ungroup%>%filter(total<=t)%>%filter(possible>=t)}
  return(df)}
```

```{r}
part1<-containercombos()
part1<-nrow(part1)
part1
```

## Part2

Slight edit to container combos

```{r}
containercombos<-function(cs=containers,t=25){
  df<-data.frame(c(0),c(0),c(0))
  colnames(df)<-c("total","possible","containercount")
  leftover<-cs
  while(length(leftover)>0){
    ct<-leftover[1]
    leftover<-leftover[-1]
    yesct<-df %>% rowwise %>% mutate(total=total+ct) %>% mutate(possible=total+sum(leftover),containercount=containercount+1) %>% ungroup 
    noct<-df %>% rowwise %>% mutate(possible=total+sum(leftover)) %>% ungroup
    df<-rbind(yesct,noct)
    df<-df%>%filter(total<=t)%>%filter(possible>=t)}
  fewest<-min(df$containercount)
  df<-df %>% ungroup %>% filter(containercount==fewest)
  return(df)}
```

```{r}
part2<-containercombos()
part2<-nrow(part2)
part2
```

