---
title: "Day 5 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(igraph)
library(ggplot2)
library(rgl)
library(ggraph)
library(readr)
library(ds4psy)
library(numbers)
options(scipen = 999)
```


## Part 1
```{r}
input <- read_lines("Day5Sample.txt")

nicelist<-as.data.frame(input)
colnames(nicelist)<-c("naughtynice")
```

Apply the rules
```{r}
nicelist <- nicelist %>%
  mutate(vowelcount=ifelse(str_count(naughtynice,"[aeiou]")>=3,TRUE,FALSE),
         dblletter=str_detect(naughtynice,"(.)\\1"),
         massdetect=str_detect(naughtynice,"ab|cd|pq|xy",negate=TRUE)) %>%
  rowwise %>% mutate(testpass=vowelcount&dblletter&massdetect) %>%
  filter(testpass==TRUE)

part1<-nrow(nicelist)
part1
```
## Part 2

Different versions of "nice"  reset and find the new patterns
```{r}
nicelist<-as.data.frame(input)
colnames(nicelist)<-c("naughtynice")

nicelist <- nicelist %>%
  mutate(betweenletters=str_detect(naughtynice,"([a-z]).\\1"),
         doubledouble=str_detect(naughtynice,"([a-z]{2}).*\\1"))%>%
         rowwise %>% mutate(testpass=betweenletters&&doubledouble)%>%
  filter(testpass==TRUE)

part2<-nrow(nicelist)
part2
```

```{r}
day5answers <-function(input){
  nicelist<-as.data.frame(input)
  colnames(nicelist)<-c("naughtynice")
  nicelist <- nicelist %>%
    mutate(vowelcount=ifelse(str_count(naughtynice,"[aeiou]")>=3,TRUE,FALSE),
           dblletter=str_detect(naughtynice,"(.)\\1"),
           massdetect=str_detect(naughtynice,"ab|cd|pq|xy",negate=TRUE)) %>%
    mutate(betweenletters=str_detect(naughtynice,"([a-z]).\\1"),
           doubledouble=str_detect(naughtynice,"([a-z]{2}).*\\1"))%>%
    rowwise %>% mutate(part1=vowelcount&dblletter&massdetect,part2=betweenletters&&doubledouble)
  part1<-sum(nicelist$part1)
  part2<-sum(nicelist$part2)
  c(part1,part2)}

```

```{r}
day5 <- day5answers(input)
day5
```