---
title: "Day 23 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(igraph)
library(ggplot2)
library(rgl)
library(ggraph)
library(readr)
library(ds4psy)
library(numbers)
library(collections)
options(scipen = 999)
```


## Part 1
```{r}
input<-read_lines("Day23Sample.txt")
```

Solving this by creating a dictionary and then just following instructions

```{r}
##create the dictionary with both a & b at 0
d23<-dict(list(a=0,b=0))
```


```{r}
### run through the instructions from the first to the last
i<-1
while(i<=length(input)){
  instruction<-input[i]
  ### split the instruction into "words" - decide what to do based on first word.
  instruction<-unlist(str_split(instruction," "))
  switch(instruction[1],
         "hlf"={
           x<-d23$get(instruction[2])
           d23$set(instruction[2],x/2)},
         "tpl"={
           x<-d23$get(instruction[2])
           d23$set(instruction[2],x*3)},
         "inc"={
           x<-d23$get(instruction[2])
           d23$set(instruction[2],x+1)},
         "jmp"={i<-i+(as.numeric(instruction[2]))
         next},
         "jie"={
           if(d23$get(str_sub(instruction[2],1,1))%%2==0){
             i<-i+(as.numeric(instruction[3]))
             next}},
         "jio"={
           if(d23$get(str_sub(instruction[2],1,1))==1){
             i<-i+(as.numeric(instruction[3]))
             next}},
         {cat("something weird happened\n")
           break})
  
  i<-i+1}
### see what's in a & b at the end
d23$as_list()
```
```{r}
part1<-d23$get("b")
part1
```

## Part 2
rerun starting with a = 1

```{r}
##create the dictionary with both a at 1 while b is 0
d23<-dict(list(a=1,b=0))

### run through the instructions from the first to the last
i<-1
while(i<=length(input)){
  instruction<-input[i]
  instruction<-unlist(str_split(instruction," "))
  switch(instruction[1],
         "hlf"={
           x<-d23$get(instruction[2])
           d23$set(instruction[2],x/2)},
         "tpl"={
           x<-d23$get(instruction[2])
           d23$set(instruction[2],x*3)},
         "inc"={
           x<-d23$get(instruction[2])
           d23$set(instruction[2],x+1)},
         "jmp"={i<-i+(as.numeric(instruction[2]))
         next},
         "jie"={
           if(d23$get(str_sub(instruction[2],1,1))%%2==0){
             i<-i+(as.numeric(instruction[3]))
             next}},
         "jio"={
           if(d23$get(str_sub(instruction[2],1,1))==1){
             i<-i+(as.numeric(instruction[3]))
             next}},
         {cat("something weird happened\n")
           break})
  
  i<-i+1}

d23$as_list()

part2<-d23$get("b")
part2
```
