---
title: "Day 8 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(igraph)
library(ggplot2)
library(rgl)
library(ggraph)
library(readr)
library(ds4psy)
library(numbers)
options(scipen = 999)
```


## Part 1
```{r}
input <- read_lines("Day8Sample.txt")
santaslist<-as.data.frame(input)
colnames(santaslist)<-c("literal")
sl<-santaslist
```

Start managing the dataframe:


```{r}
santaslist<-sl
##remove the quote marks on the edge
santaslist <- santaslist %>% mutate(outsidequotes=str_sub(literal,2,-2))
##remove double backslashes
santaslist <- santaslist %>%
  mutate(doubleback=str_replace_all(outsidequotes,"\\\\{2}","\\\\"))
##remove interior quotes
santaslist <- santaslist %>%
  mutate(insidequotes=str_replace_all(doubleback,"\\\\\"","\""))
## quick convert all the hexes to a tilde.
santaslist <- santaslist %>%
  mutate(parsethex=str_replace_all(insidequotes,"\\\\x([0123456789abcdef][0123456789abcdef])","X"))
##count
santaslist <- santaslist %>%
  mutate(lit_length=nchar(literal),val_length=nchar(parsethex)) %>%
  mutate(part1=lit_length-val_length)

part1<-sum(santaslist$part1)
part1
```
* note, this does not work for three backslashes in a row followed by a quote.  I don't know why not.

## Part 2

This is right (add 1 for every slash, 1 for every interior quote and 1 for every exterior quote)
```{r}
part2 <- str_count(input,"\\\\")+2+str_count(input,"\\\"")
part2<-sum(part2)

part2
```